### ISSUE TITLE
cp failed source file dose not exist.

### ISSUE THREAD

**Issue by ynott** [sue445/jenkins-backup-script#19]
+ mkdir -p /root/backup/tmp/jenkins-backup/jobs/XXXX-pull/
+ cp '/var/lib/jenkins/jobs/dphelp-pull/*.xml' /root/backup/tmp/jenkins-backup/jobs/XXXX-pull/
cp: cannot stat `/var/lib/jenkins/jobs/XXXX-pull/*.xml': そのようなファイルやディレクトリはありません

Failed on line: 43 
SouceFile missing

**Comment by sue445** [comment]
@ynott Shall I close issue ?

**Comment by ynott** [comment]
Yes, sure.
Thanks.

**Comment by sue445** [comment]
:smile:
