### ISSUE TITLE
cp: cannot stat `/path/to/jenkins/users/*': No such file or directory

### ISSUE THREAD

**Issue by taitranvn** [sue445/jenkins-backup-script#28]
I'm using Jenkins build 1608 and the script 0.1.0. It ran with the error below:
...
+ cp -R '/home/TaiTT/apg/jenkins/users/*' '/home/TaiTT/apg/jenkins/workspace/Jenkins Weekly Backup/tmp/jenkins-backup/users'
cp: cannot stat `/home/TaiTT/apg/jenkins/users/*': No such file or directory
Build step 'Execute shell' marked build as failure
[ExclusiveBuildWrapper] Canceling Jenkins shutdown mode... 
Finished: FAILURE

**Comment by sue445** [comment]
@taitranvn Sorry, this is fixed #27, but I forgot release :sweat_smile: 
Please try current master

**Comment by taitranvn** [comment]
Thanks, I created users and an empty file in it as a workaround though.

**Comment by sue445** [comment]
:smile:
