### ISSUE TITLE
Wrong place for backup

### ISSUE THREAD

**Issue by PaulWoitaschek** [sue445/jenkins-backup-script#30]
I used the script from `/root` with the command `./jenkins-backup-script/ /var/lib/jenkins archive.tar.gz`. I expected to now have a file called `/root/archive.tar.gz`. 

However the console prints
> \+ mv -f /root/jenkins-backup-script/tmp/archive.tar.gz archive.tar.gz
mv: '/root/jenkins-backup-script/tmp/archive.tar.gz' and 'archive.tar.gz' are the same file

and my backup is in `/root/jenkins-backup-script/tmp/archive.tar.gz`

**Comment by sue445** [comment]
`cd tmp/` before `mv`

https://github.com/sue445/jenkins-backup-script/blob/08e45dd4ee383481e8baee29f25840f43b24afd9/jenkins-backup.sh#L50

I recommend to the to use the absolute path

**Comment by PaulWoitaschek** [comment]
What you mean by that? That's what the script did, I just ran the command.
If found this unexpected and it seems to me like a bug.

**Comment by sue445** [comment]
This feature is merged #31 and released as v0.1.2
