### ISSUE TITLE
Script fails when a folder exists with no jobs in it

### ISSUE THREAD

**Issue by leemeador** [sue445/jenkins-backup-script#50]
The title says it all. You can't cd to the jobs folder when it hasn't been created yet since the folder is new and hasn't had any jobs added yet.

Here's how it can be fixed:

In backup-jenkins.sh line 51 says 

`    cd "$run_in_path"
`
Add this line before it and a corresponding "fi" after the "done"

`     if [ -d "$run_in_path" ] ; then
`

I know, I'm being lazy and not submitting a patch. Sorry. Never done that on GitHub before and don't want to learn for a single line. Someday ...

**Comment by sue445** [comment]
Resolved at #52

**Comment by sue445** [comment]
Release v0.1.9
